name: flutter_neumorphic
description: A complete, ready to use, Neumorphic ui kit for Flutter. Dark theming compatible & fully customizable.
version: 4.0.0
homepage: https://github.com/OneCoser/flutter_neumorphic

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: NeumorphicIcons
      fonts:
        - asset: fonts/NeumorphicIcons.ttf